name: Duty Bot

on:
  schedule:
    - cron: "30 1 * * *"   # UTC 2:30 = 北京时间 10:30
  workflow_dispatch:        # 支持手动触发

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        env:
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
        run: python bot.py
